# Generated by Django 4.1.1 on 2022-11-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_alter_tarefas_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(blank=True, default='pendente', max_length=200, null=True),
        ),
    ]
