# Generated by Django 4.1.1 on 2022-11-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_alter_tarefas_date_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='date_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='date_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='date_start',
            field=models.DateField(),
        ),
    ]
