# Generated by Django 4.1.3 on 2022-12-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0009_alter_tarefas_date_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='date_completion',
            field=models.DateTimeField(),
        ),
    ]
